services:
  app_user:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      DB_URL: jdbc:mysql://amazon_user:3306/amazon_users?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 123456789
    restart: always
    depends_on:
      amazon_user:
        condition: service_healthy

  amazon_user:
    image: mysql:8.0.33
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: amazon_users
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p123456789"]
      timeout: 10s
      retries: 10